version: "3"
services:
  react:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "80:3000"
    volumes:
      - /app/node_modules
      - .:/app
    # Windows에서 실시간 반영을 위한 설정
    environment:
      - CHOKIDAR_USEPOLLING=true
    # 기본 입력을 연결한다.
    stdin_open: true
  test:
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    stdin_open: true
    command: ["npm", "test"]